var Tag=function(){var j={},d={isArray:function(a){return Array.isArray?Array.isArray(a):Object.prototype.toString.call(a)=="[object Array]"},mixin:function(a){for(var b=1;b<arguments.length;b++)if(arguments[b]){for(var c in arguments[b])if(arguments[b].hasOwnProperty(c))a[c]=arguments[b][c];if(arguments[b].hasOwnProperty("toString"))a.toString=arguments[b].toString}return a},create:function(a){a=a||{};var b=typeof this=="function"?this:Object;if(!a.hasOwnProperty("constructor"))a.constructor=function(){b.apply(this,
arguments)};var c=function(){};c.prototype=b.prototype;a.constructor.prototype=new c;for(var f in a)if(a.hasOwnProperty(f))a.constructor.prototype[f]=a[f];a.constructor.superclass=b.prototype;a.constructor.inherit=d.create;return a.constructor},"":""};d.Observer=d.create({constructor:function(){this.Bricks_Observer__listeners={}},addEventListener:function(a,b){this.Bricks_Observer__listeners[a]=this.Bricks_Observer__listeners[a]||[];this.Bricks_Observer__listeners[a].push(b)},removeEventListener:function(a,
b){if(this.Bricks_Observer__listeners[a])for(var c=0;c<this.Bricks_Observer__listeners.length;c++)this.Bricks_Observer__listeners[c]==b&&this.Bricks_Observer__listeners.splice(c,1)},_fireEvent:function(a,b){var c=this.Bricks_Observer__listeners[a]||[];if(this.Bricks_Observer__listeners["*"])c=c.concat(this.Bricks_Observer__listeners["*"]);for(var f=d.mixin({},b,{type:a,target:this}),e=c.length-1;e>=0;e--)try{if(c[e].call(this,f)===false)return false}catch(g){this._handleListenerError(g)}return true},
_handleListenerError:function(a){setTimeout(function(){throw a;},10)}});d.Component=d.Observer.inherit({constructor:function(a){d.Component.superclass.constructor.apply(this,arguments);this._initialConfig=a||{};for(var b in this._initialConfig)if(this._initialConfig.hasOwnProperty(b))this[b]=this._initialConfig[b];this._initComponent()},_initComponent:function(){},_getPrototypeChain:function(a){for(var b=this.hasOwnProperty(a)?[this]:[],c=this.constructor.prototype;c!=d.Component.prototype;){c.hasOwnProperty(a)&&
b.push(c);c=c.constructor.superclass}return b}});d.String={trim:function(a){return a.replace(/^\s+|\s+$/g,"")},escapeHTML:function(a){var b=document.createElement("DIV");a=document.createTextNode(a);b.appendChild(a);return b.innerHTML},camelize:function(a){return a.replace(/-([a-z])/g,function(b,c){return c.toUpperCase()})},uncamelize:function(a){return a.replace(/[A-Z]/g,function(b){return"-"+b.toLowerCase()})},compile:function(a){function b(e){for(e=e.charCodeAt(0).toString(16);e.length<4;)e="0"+
e;return"\\u"+e}var c="$_"+Math.round(Math.random()*1E9),f=["var ",c,"=[];"];f.push(a.replace(/(<%((&)?=)?(.*?)%>)|([\s\S]+?(?=(<%|$)))/g,function(e,g,h,i,k){return(g?h?i?[c,".push(",k,");"]:[c,".push(arguments.callee.escapeHTML(String(",k,")));"]:[k,"\n"]:[c,'.push("',e.replace(/./g,b),'");']).join("")}));f.push("return ",c,'.join("");');a=new Function(f.join(""));a.escapeHTML=d.String.escapeHTML;return a},"":""};d.Event={"":""};d.DOM={getEl:function(a,b){return typeof a=="string"?(b||document).getElementById(a):
a},getEls:function(a,b){b||(b=[document]);d.isArray(b)||(b=[b]);if(a.charAt(0)=="!"){var c=true;a=a.substr(1)}for(var f=d.DOM.createSelectorFilter(a),e=[],g=0;g<b.length;g++)for(var h=d.DOM.getEl(b[g]).getElementsByTagName(a.split(".")[0]||"*"),i=0;i<h.length;i++)if(f(h[i])){if(c)return h[i];e.push(h[i])}return c?null:e},createSelectorFilter:function(a){this.Bricks_DOM__selectors=this.Bricks_DOM__selectors||{};a=d.String.trim(a);if(!this.Bricks_DOM__selectors[a]){var b=a.split("."),c=b[0].toUpperCase();
b=b[1];var f=[];c&&c!="*"&&f.push('e.tagName=="'+c.replace(/"/g,"\\u0022")+'"');b&&f.push("e.className && e.className.match && e.className.match(/(^|\\s)"+b+"(\\s|$)/)");this.Bricks_DOM__selectors[a]=new Function("e","return "+(f.join("&&")||"true"))}return this.Bricks_DOM__selectors[a]},setStyle:function(a,b){a=d.DOM.getEl(a);for(var c in b)if(b.hasOwnProperty(c)){var f=d.DOM.normalizeCSSProperty(c,b[c]);a.style[f[0]]=f[1]}},getPos:function(a){a=d.DOM.getEl(a);if(a.getBoundingClientRect){var b=a.getBoundingClientRect(),
c=a.ownerDocument;a=d.DOM.getDocumentScroll(c);c=d.DOM.getRootElement(c);return[b.left+a[0]-(c.clientLeft||0),b.top+a[1]-(c.clientTop||0)]}else{for(c=b=0;a;){b+=parseInt(a.offsetLeft);c+=parseInt(a.offsetTop);a=a.offsetParent}return[b,c]}},getSize:function(a){a=d.DOM.getEl(a);return[a.offsetWidth,a.offsetHeight]},classNameExists:function(a,b){return RegExp("(^|\\s)"+d.String.trim(b)+"(\\s|$)","").test(d.DOM.getEl(a).className)},addClassName:function(a,b){if(!d.DOM.classNameExists(a,b)){d.DOM.getEl(a).className+=
" "+b;return true}return false},removeClassName:function(a,b){a=d.DOM.getEl(a);var c=a.className.replace(RegExp("(^|\\s)"+b+"(?=\\s|$)","g")," ");if(c!=a.className){a.className=c;return true}return false},toggleClassName:function(a,b,c){if(arguments.length<3)c=!d.DOM.classNameExists(a,b);return c?d.DOM.addClassName(a,b):d.DOM.removeClassName(a,b)},on:function(a,b,c,f){a=d.DOM.getEl(a);var e=this.Bricks_DOM__listeners=this.Bricks_DOM__listeners||{};b=b.split(",");for(var g=0;g<b.length;g++){var h=
d.String.trim(b[g]);e[h]=e[h]||[];var i=function(k){c.call(f,k||window.event)};e[h].push([a,c,f,i]);if(a.addEventListener)a.addEventListener(h,i,false);else a.attachEvent&&a.attachEvent("on"+h,i)}},un:function(a,b,c,f){a=d.DOM.getEl(a);if(this.Bricks_DOM__listeners){b=b.split(",");for(var e=0;e<b.length;e++)for(var g=this.Bricks_DOM__listeners[d.String.trim(b[e])]||[],h=0;h<g.length;h++){var i=g[h];if(i[0]==a&&i[1]==c&&i[2]==f){g.splice(h,1);if(a.removeEventListener)a.removeEventListener(event,i[3],
false);else a.detachEvent&&a.detachEvent("on"+event,i[3]);return}}}},getWindow:function(a){a=a||document;return a.parentWindow||a.defaultView},getRootElement:function(a){a=a||document;return a.compatMode=="CSS1Compat"?a.documentElement:a.body},getDocumentScroll:function(a){a=a||document;var b=d.DOM.getWindow(a);return[b.pageXOffset||a.documentElement.scrollLeft||a.body.scrollLeft||0,b.pageYOffset||a.documentElement.scrollTop||a.body.scrollTop||0]},normalizeCSSProperty:function(a,b,c){var f=c?c.style:
document.documentElement.style;a=d.String.camelize(a);if(a=="opacity"&&typeof f.opacity!="string")return["filter",b==1?"":"Alpha(opacity="+b*100+")"];if(a=="float"){if(c)a=typeof f.cssFloat=="string"?"cssFloat":"styleFloat";return[a,b]}if(typeof f[a]!="string"){c=["Moz","Webkit","O","Opera"];for(var e=d.String.camelize("-"+a),g=0;g<c.length;g++)if(typeof f[c[g]+e]=="string")return[c[g]+e,b]}return[a,b]},"":""};d.AbstractWidget=d.Component.inherit({renderTo:null,tagName:"div",className:"",css:{},html:"",
doc:null,_initComponent:function(){d.AbstractWidget.superclass._initComponent.apply(this,arguments);if(this.renderTo)this.renderTo=d.DOM.getEl(this.renderTo);if(!this.doc)this.doc=this.renderTo?this.renderTo.ownerDocument:document;this._buildCss()},destroy:function(){this._fireEvent("destroy")},_getClassNames:function(){for(var a=this._getPrototypeChain("className"),b=[],c=0;c<a.length;c++)b.push(a[c].className);return b.join(" ")},_buildCss:function(){for(var a=this._getPrototypeChain("css"),b=[],
c=0;c<a.length;c++){if(!a[c].hasOwnProperty("Bricks_AbstractWidget__docs"))a[c].Bricks_AbstractWidget__docs=[];for(var f=true,e=0;e<a[c].Bricks_AbstractWidget__docs.length;e++)if(a[c].Bricks_AbstractWidget__docs[e]==this.doc){f=false;break}if(f){a[c].Bricks_AbstractWidget__docs.push(this.doc);b.unshift(this._compileCSSRule("",a[c].css))}}if(a=d.String.trim(b.join(""))){b=this.doc.createElement("style");b.type="text/css";if(b.styleSheet)b.styleSheet.cssText=a;else if(b.innerText=="")b.innerText=a;
else b.innerHTML=a;this.doc.getElementsByTagName("head")[0].appendChild(b)}},_compileCSSRule:function(a,b){var c=[],f=[],e;for(e in b)if(b.hasOwnProperty(e)){var g=b[e];if(typeof g=="object")if(/^[?^] /.test(e)){var h=typeof this.doc.documentElement.style[d.DOM.normalizeCSSProperty(e.substr(2),"")[0]]=="string";(e.charAt(0)=="?"&&h||e.charAt(0)=="^"&&!h)&&c.push(this._compileCSSRule(a,g))}else c.push(this._compileCSSRule(a+" "+e,g));else{g=d.DOM.normalizeCSSProperty(e,g);f.push("    ",d.String.uncamelize(g[0]),
": ",g[1],";\n")}}return(a?[a," {\n",f.join(""),"}"].join(""):"")+c.join("")},_applyTemplate:function(a){return a?d.String.compile(a).call(this):""}});d.Widget=d.AbstractWidget.inherit({namespace:"",_initComponent:function(){d.Widget.superclass._initComponent.apply(this,arguments);this._el=this.namespace?this.doc.createElementNS(this.namespace,this.tagName):this.doc.createElement(this.tagName);if(this.className){var a=this._getClassNames();if(this.namespace)this._el.setAttribute("class",a);else this._el.className=
a}if(this.html)this._el.innerHTML=this._applyTemplate(this.html);this.renderTo&&this.renderTo.appendChild(this._el)},destroy:function(){d.DOM.remove(this.getEl());d.Widget.superclass.destroy.apply(this,arguments)},getEl:function(){return this._el},_getEl:function(a,b){this.Bricks_Widget__elementsCache=this.Bricks_Widget__elementsCache||{};if(a){if(!this.Bricks_Widget__elementsCache[a]||b)this.Bricks_Widget__elementsCache[a]=d.DOM.getEls("!."+a,this._el);return this.Bricks_Widget__elementsCache[a]}return this._el},
_classNameExists:function(a,b){if(arguments.length==1){b=a;a=""}return d.DOM.classNameExists(this._getEl(a),b)},_addClassName:function(a,b){if(arguments.length==1){b=a;a=""}return d.DOM.addClassName(this._getEl(a),b)},_removeClassName:function(a,b){if(arguments.length==1){b=a;a=""}return d.DOM.removeClassName(this._getEl(a),b)},_toggleClassName:function(a,b,c){if(arguments.length==1||arguments.length==2&&typeof b!="string"){c=b;b=a;a=""}return d.DOM.toggleClassName(this._getEl(a),b,c)},_on:function(a,
b,c){if(arguments.length<3){c=b;b=a;a=""}a=a||"";d.DOM.on(typeof a=="string"?this._getEl(a):a,b,c,this)},_un:function(a,b,c){if(arguments.length<3){c=b;b=a;a=""}a=a||"";d.DOM.un(typeof a=="string"?this._getEl(a):a,b,c,this)},_getElPos:function(a){return d.DOM.getPos(this._getEl(a))},_getElSize:function(a){return d.DOM.getSize(this._getEl(a))},_setStyle:function(a,b){if(arguments.length==1){b=a;a=""}d.DOM.setStyle(this._getEl(a),b)},_getEls:function(a){return d.DOM.getEls("."+a,this._el)}});j.Number=
d.Widget.inherit({number:1,tagName:"span",className:"tag-game-number",css:{".tag-game-number":{"font-weight":"bold",display:"inline-block",width:"30px",height:"30px","text-align":"center","line-height":"30px","vertical-align":"middle",cursor:"pointer",border:"2px solid #555","border-radius":"5px"}},html:"<%= this.number %>",_initComponent:function(){j.Number.superclass._initComponent.apply(this,arguments);this._on("click",this.TagGame_Number__onClick)},getNumber:function(){return this.number},TagGame_Number__onClick:function(){this._fireEvent("click")}});
d.Function={defer:function(a,b,c,f){return window.setTimeout(function(){a.apply(c,f||[])},b)},"":""};j.Field=d.Widget.inherit({className:"tag-game-field",css:{".tag-game-field__table":{"border-collapse":"collapse"},".tag-game-field__cell":{width:"40px",height:"40px",padding:"0","text-align":"center","vertical-align":"middle",border:"2px solid #CCC"}},html:'<table class="tag-game-field__table"><% for (var i = 0; i < 4; i++) { %><tr><% for (var j = 0; j < 4; j++) { %><td class="tag-game-field__cell"></td><% } %></tr><% } %></table>',
_initComponent:function(){j.Field.superclass._initComponent.apply(this,arguments);this._shuffling=false;this._numbers=Array(16);for(var a=0;a<15;a++){var b=new j.Number({number:a+1,renderTo:this._getEl("tag-game-field__table").rows[Math.floor(a/4)].cells[a%4]});this._on(b,"click",this.TagGame_Field__onNumberClick);this._numbers[a]=b}},move:function(a){var b=this._getNumberByCell(a);if(b){for(var c=this._getSiblingCells(a),f=null,e=0;e<c.length;e++)if(!this._getNumberByCell(c[e])){f=c[e];break}if(f){this._numbers[this._getIndexByCell(f)]=
b;this._numbers[a[0]*4+a[1]]=null;this._getEl("tag-game-field__table").rows[f[0]].cells[f[1]].appendChild(b.getEl());this._shuffling||this._fireEvent("move")}}},shuffle:function(a,b,c){this._shuffling=true;(function(f){if(f<a){var e=this._getSiblingCells(this._findEmptyCell());this.move(e[Math.floor(Math.random()*e.length)]);d.Function.defer(arguments.callee,50,this,[f+1])}else{this._shuffling=false;b&&b.call(c)}}).call(this,0)},isComplete:function(){for(var a=0;a<15;a++)if(!this._numbers[a]||this._numbers[a].getNumber()!=
a+1)return false;return true},_getNumberByCell:function(a){return this._numbers[this._getIndexByCell(a)]},_getSiblingCells:function(a){var b=[];a[0]>0&&b.push([a[0]-1,a[1]]);a[1]<3&&b.push([a[0],a[1]+1]);a[0]<3&&b.push([a[0]+1,a[1]]);a[1]>0&&b.push([a[0],a[1]-1]);return b},_getIndexByCell:function(a){return a[0]*4+a[1]},_getCellByNumber:function(a){for(var b=0;b<this._numbers.length;b++)if(this._numbers[b]==a)return[Math.floor(b/4),b%4]},_findEmptyCell:function(){for(var a=0;a<this._numbers.length;a++)if(!this._numbers[a])return[Math.floor(a/
4),a%4]},TagGame_Field__onNumberClick:function(a){this._shuffling||this.move(this._getCellByNumber(a.target))}});j.Game=d.Widget.inherit({className:"tag-game-game",css:{".tag-game-game":{width:"170px"},".tag-game-game__ctrls":{padding:"10px","text-align":"center"}},html:'<div class="tag-game-game__field"></div><div class="tag-game-game__ctrls"><button class="tag-game-game__shuffle">\u041f\u0435\u0440\u0435\u043c\u0435\u0448\u0430\u0442\u044c</button></div>',_initComponent:function(){j.Game.superclass._initComponent.apply(this,
arguments);this._field=new j.Field({renderTo:this._getEl("tag-game-game__field")});this._on("tag-game-game__shuffle","click",this.TagGame_Game__onShuffleClick);this._on(this._field,"move",this.TagGame_Game__onMoveNumber)},shuffle:function(a,b,c){this._getEl("tag-game-game__shuffle").disabled=true;this._field.shuffle(a,function(){this._getEl("tag-game-game__shuffle").disabled=false;b&&b.call(c)},this)},TagGame_Game__onShuffleClick:function(){this.shuffle(100)},TagGame_Game__onMoveNumber:function(){this._field.isComplete()&&
this._fireEvent("win")}});return j.Game}();
